# Generated by Django 3.1.2 on 2021-01-31 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_followers_follows_likes_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Follows', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followee', to=settings.AUTH_USER_MODEL)),
                ('users_who_Follows', models.ManyToManyField(blank=True, related_name='followees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='userFollowed',
            new_name='user_Followed',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='usersFollowers',
            new_name='users_Followers',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='wholikedit',
            new_name='who_liked_it',
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
