# Generated by Django 3.1.2 on 2021-02-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210202_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='who_liked_it',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_or_not',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
