# Generated by Django 3.1.2 on 2021-02-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210203_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_or_not',
            field=models.BooleanField(default=True),
        ),
    ]
