# Generated by Django 3.1.2 on 2021-02-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210204_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
