# Generated by Django 3.1.2 on 2021-02-08 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20210205_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_who_liked',
        ),
        migrations.AddField(
            model_name='post',
            name='user_who_liked',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
