# Generated by Django 3.1.2 on 2021-02-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210212_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_or_not',
        ),
        migrations.RemoveField(
            model_name='like',
            name='number_of_likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
